config/routes.rb
Rails.application.routes.draw do
  resources :clientes

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	def self.search(search, page)
	where(['upper(nombre) like ?',
	"%#{search}%".upcase]).paginate(page: page, per_page: 3).order("nombre")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.search(params[:search], params[:page])
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:cedula, :nombre, :fch_ncto, :mail, :genero, :celular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
	def mostrar_genero(genero)
	     if genero
	"Masculino"
	else
	"Femenino"
	     end
	end
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :fch_ncto %><br>
    <%= f.date_select :fch_ncto %>
  </div>
  <div class="field">
    <%= f.label :mail %><br>
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    Masculino: <%= f.radio_button(:genero, true) %>
    Femenino: <%= f.radio_button(:genero, false) %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to 'Ver', @cliente %> |
<%= link_to 'Atras', clientes_path %>

app/views/clientes/index.html.erb
<h1>Lista Clientes</h1>

  <%= form_tag clientes_path, :method => 'get' do %>
  <% content_tag :label do %>
  Search term:
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Buscar", :name => nil %>
  <% end %>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Nombre</th>
      <th>Fch ncto</th>
      <th>Mail</th>
      <th>Genero</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.cedula %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.fch_ncto %></td>
        <td><%= cliente.mail %></td>
        <td><%= cliente.genero %></td>
        <td><%= cliente.celular %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

<%= will_paginate @clientes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Clientes: <%= @clientes.count %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Atras', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @cliente.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Fch ncto:</strong>
  <%= @cliente.fch_ncto %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @cliente.mail %>
</p>

<p>
  <strong>Genero:</strong>
  <%= mostrar_genero(@cliente.genero) %>
</p>


<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Atras', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Samo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>